version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:postgresql_db
    secrets:
      - postgres_password
  postgresql_db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: platepal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
secrets:
  postgres_password:
    file: ./postgres_password.txt
