spring:
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url: jdbc:postgresql://postgresql_db:5432/platepal
    username: postgres
    password: ${postgres_password}
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
plate-pal:
  security:
    jwtSecret: ${jwt_secret}
    jwtExpirationDays: 30

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/platepal
    password: ${PG_PASSWORD}
